function sample_edges = generate_sample_edges( width, height, sample_width, sample_height, x_increment, y_increment )
%GENERATE_SAMPLE_EDGES Creates edge positions of samples generated by
%sample_image
%   width - the width of the original image
%   height - the height of the original image
%   sample_width - the width of each sample to take
%   sample_height - the height of each sample to take
%   x_increment - difference between each sample in the x direction
%   y_increment - difference between each sample in the y direction

left = 1;
right = left + sample_width - 1;
top = 1;
bottom = top + sample_height - 1;
sample_edges = [];
while right <= width
    while bottom <= height
        sample_edge = [top; bottom; left; right];
        sample_edges = cat(2, sample_edges, sample_edge);
        top = top + y_increment;
        bottom = bottom + y_increment;
    end
    top = 1;
    bottom = top + sample_height - 1;
    left = left + x_increment;
    right = right + x_increment;
end
end

